# Site settings
title: 'Bikash-Jaiswal Blog'
description: 'You have the capacity to learn from your mistakes, and you will learn a lot today.'
url: 'http://bikash-jaiswal.github.io' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  about: '/about.html'
  tags: '/tags.html'


# Footer
footer:
  since: 2017

# Author
author: 'bikash'
nickname: 'bikash'
bio: ''
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: true

 # Scripts
google_analytics: UA-121120223-1

# Comments
comments:
  disqus: true
  disqus_url: 'https://bikash-jaiswal.disqus.com/embed.js'

# MathJax  by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['github', 'linkedin']

# theme color
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  linkedin: 'https://www.linkedin.com/in/bikashjaiswal'
  github: 'https://www.github.com/bikash-jaiswal'
  email: 'bjjaiswal@gmail.com'

# Tags
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'blog/page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins_dir: [jekyll-paginate]
